---
- hosts: web
  sudo: yes
  nvm:
    user: deploy
    version: v0.25.4
    node_version: '0.12.4'

  tasks:

  - name: Install dependencies
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - git
      - curl
      - build-essential
      - libssl-dev

  - name: Install nvm
    sudo: yes
    sudo_user: "{{ nvm.user }}"
    git: repo=https://github.com/creationix/nvm.git dest=~/.nvm version={{ nvm.version }}
    tags: nvm

  - name: Source nvm in ~/.profile
    sudo: yes
    sudo_user: "{{ nvm.user }}"
    lineinfile: >
      dest=~/.profile
      line="source ~/.nvm/nvm.sh"
    tags: nvm

  - name: Install {{ nvm.node_version }}
    command: sudo -iu {{ nvm.user }} nvm install {{ nvm.node_version }}
    register: nvm_install_result
    changed_when: "'is already installed.' not in nvm_install_result.stdout"
    tags: nvm

  - name: Check if {{ nvm.node_version }} is the default node version
    shell: sudo -iu {{ nvm.user }} nvm ls | grep -e 'default -> {{ nvm.node_version }}'
    register: nvm_check_default
    changed_when: False
    ignore_errors: True
    tags: nvm

  - name: Set default node version to {{ nvm.node_version }}
    command: sudo -iu {{ nvm.user }} nvm alias default {{ nvm.node_version }}
    when: nvm_check_default|failed
    tags: nvm