---
- hosts: web
  sudo: yes

  tasks:

  - name: Install dependencies
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - git

  - name: Install server
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - nginx